name: Release

on:
  workflow_dispatch: {}

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: 'Get Version'
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Flow.Launcher.Plugin.WTFIsMyIP\plugin.json'
          prop_path: 'Version'
      - name: Build
        run: |
          dotnet publist 'Flow.Launcher.Plugin.WTFIsMyIP\Flow.Launcher.Plugin.WTFIsMyIP.csproj' -r win-x64 -c Release -o "WTFIP-${{steps.version.outputs.prop}}"
          7z a -tzip "WTFIP-${{steps.version.outputs.prop}}.zip" "WTFIP-${{steps.version.outputs.prop}}/*"
      - name: Publish
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: "WTFIP-${{steps.version.outputs.prop}}.zip"
          tag_name: "${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
